//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_dept { get; set; }
        public Nullable<decimal> Mobile_Number { get; set; }
        public string Emp_Address { get; set; }
    }
}
